### ISSUE TITLE
weired display on anaconda.org

### ISSUE THREAD

**Issue by bernt-matthias** [conda-forge/openjdk-feedstock#116]
### Comment:

When I open https://anaconda.org/conda-forge/openjdk

the description reads: `GraalPy is a high-performance Python implementation on GraalVM. See https://conda-forge.org/blog/posts/2020-03-10-pypy for more information about using it in conda, replacing PyPy/pypy/pp with GraalPy/graalpy/gp in commands. `

Also the link is wrong.

Files look good (but I have not tested.

Looks fishy to me....

**Comment by h-vetinari** [comment]
This is because both this feedstock and https://github.com/conda-forge/graalpy-feedstock have an output that's called `openjdk`, and only one (the most recent uploader?) gets to set the description of the package on https://anaconda.org/conda-forge/openjdk.

It's nothing to worry about, but I'll open an issue there so they can set the same `about:` for that output.

**Comment by bernt-matthias** [comment]
Excellent 👌
